name: "Site Senhor Sorvete - CD"
description: "CD - Deploy do site Senhor Sorvete para Docker"

on:
  push:
    branches:
      - main

jobs:
  cd_deploy_job:
    runs-on: ubuntu-latest
    name: CD - Build, Push Docker Image and Deploy
    steps:
      - uses: actions/checkout@v3
        with:
          submodules: true
          lfs: false

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      - name: Install dependencies and build
        run: |
          cd senhor-sorvete
          npm install
          npm run build

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build and push Docker image
        uses: docker/build-push-action@v4
        with:
          context: senhor-sorvete
          file: senhor-sorvete/Dockerfile
          push: true
          tags: ${{ secrets.DOCKER_USERNAME }}/senhorsorvete:latest
          cache-from: type=gha
          cache-to: type=gha,mode=max

      - name: Deploy to Docker server
        uses: appleboy/ssh-action@v0.1.10
        with:
          host: ${{ secrets.SERVER_HOST }}
          username: ${{ secrets.SERVER_USERNAME }}
          key: ${{ secrets.SERVER_SSH_KEY }}
          script: |
            docker pull ${{ secrets.DOCKER_USERNAME }}/senhorsorvete:latest
            docker stop senhor-sorvete || true
            docker rm senhor-sorvete || true
            docker run -d --name senhor-sorvete -p 80:80 ${{ secrets.DOCKER_USERNAME }}/senhorsorvete:latest
